FROM golang:1.24.2

# Set the working directory
WORKDIR /app

# Copy only the Go module files first (for caching)
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build from /app
RUN go build -o twitchbot .

CMD ["./twitchbot", "--port=5432"]
