services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"  

  twitchbot:
    build:
      context: ./twitchbot
      dockerfile: Dockerfile 
    container_name: twitchbot
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  pgdata:
